# -*- coding: utf-8 -*-
"""Football_Dictionaries_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZJsMpiJyG66upGSwXTnI1GvlGjL3rji

**Assignment 1 - Lists to Dicts**
"""

def list_to_dict(list_Squads):
  SQUADS_DATA_DCIT_IN_LIST=[]
  for Squads in list_Squads:
    dict_SQUADS = {
      'number': Squads[0],
      'position': Squads[1],
      'name': Squads[2],
      'date_of_birth': Squads[3],
      'caps': Squads[4],
      'club': Squads[5],
      'country': Squads[6],
      'club_country': Squads[7],
      'year':Squads[8]
      }
    SQUADS_DATA_DCIT_IN_LIST.append(dict_SQUADS)
  return SQUADS_DATA_DCIT_IN_LIST

SQUADS_DATA = [
  [
    "1",                                     # Number
    "GK",                                    # Position
    "Juan Botasso",                          # Name
    "(1908-10-23)23 October 1908 (aged 21)", # Date of Birth
    "",                                      # Caps
    "Quilmes",                               # Club
    "Argentina",                             # Country (Players Country)
    "Argentina",                             # Club Country
    "1930"                                   # Year
  ],
  [
    "9",
    "FW",
    "Roberto Cherro",
    "(1907-02-23)23 February 1907 (aged 23)",
    "",
    "Boca Juniors",
    "Argentina",
    "Argentina",
    "1930"
  ]
  # More Players...
]
SQUADS_DATA_A1 = list_to_dict(SQUADS_DATA)
print(SQUADS_DATA_A1)

"""**Assignment 2**"""

def players_position(multiple_players):
  player_Dict= {}
  for player in multiple_players:
    position = player['position']
    player_Dict.setdefault(position, [])
    player_Dict[position].append(player)
  return player_Dict

SQUADS_DATA_A2 = players_position(SQUADS_DATA_A1)
print(SQUADS_DATA_A2)

"""**Assignment 3**"""

def players_country(multiple_players):
    player_Dict_country = {}
    for player in multiple_players:
        country = player['country']
        position = player['position']

        if country not in player_Dict_country:
            player_Dict_country[country] = {}
        if position not in player_Dict_country[country]:
            player_Dict_country[country][position] = []

        player_Dict_country[country][position].append(player)

    return player_Dict_country

SQUADS_DATA_A3 = players_country(SQUADS_DATA_A1)
print(SQUADS_DATA_A3)